name: Gitbub Actions 실행시켜보기

on:
  push:
    branches: 
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"

      - neme: 여러 명렁어 작성
        run: |
          echo "앙"
          echo "몽실"
          pwd